# Generated by Django 2.2.20 on 2021-06-05 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rcvserver', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poll',
            name='limit_choices_added',
        ),
    ]
