# Generated by Django 2.2.20 on 2021-06-05 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rcvserver', '0002_remove_poll_limit_choices_added'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='limit_choices_added',
            field=models.IntegerField(default=None),
        ),
    ]
