# Generated by Django 2.2.20 on 2021-06-06 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rcvserver', '0004_poll_users_can_add_choices'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='parent',
            field=models.CharField(default=None, max_length=24),
        ),
    ]
