# Generated by Django 2.2.20 on 2021-06-06 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rcvserver', '0006_poll_allow_users_to_see_archived_polls'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='allow_users_to_edit_ballots',
            field=models.BooleanField(default=True),
        ),
    ]
