# Generated by Django 2.2.20 on 2021-06-06 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rcvserver', '0007_poll_allow_users_to_edit_ballots'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='ballots_must_be_full',
            field=models.BooleanField(default=False),
        ),
    ]
