# Generated by Django 2.2.20 on 2021-10-15 04:01

from django.db import migrations
import djongo.models.fields
import rcvserver.models


class Migration(migrations.Migration):

    dependencies = [
        ('rcvserver', '0010_customlanguage'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='custom_language',
            field=djongo.models.fields.EmbeddedField(default=rcvserver.models.CustomLanguage, model_container=rcvserver.models.CustomLanguage, null=True),
        ),
    ]
